format_version: 10
pipelines:
  backend:
    group: APP-deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a69cea3:
        git: https://github.com/addydevops17011/ansible-expense
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls

      - QA:
          fetch_materials: true
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed